- Cargo.lock
- crates/agglayer-certificate-orchestrator/Cargo.toml
- crates/agglayer-certificate-orchestrator/src/lib.rs
- crates/agglayer-certificate-orchestrator/src/tests.rs
- crates/agglayer-config/src/certificate_orchestrator.rs
- crates/agglayer-config/src/lib.rs
- crates/agglayer-node/Cargo.toml
- crates/agglayer-node/src/node.rs
- crates/agglayer-node/src/node/notifier.rs
This PR introduces the `certificate-orchestrator`. 
The `certificate-orchestrator` is responsible for collecting the `certificates` coming from the CDKs (from JSON-RPC) and creating `epoch_packing` task when an Epoch ends.
The `epoch_packing` task implementation remains open and is not part of this PR.
This PR is part of #45
> feat: adding certificate-orchestrator

- .github/workflows/test.yml
- crates/agglayer-certificate-orchestrator/src/lib.rs
- crates/agglayer-clock/src/block.rs
- crates/agglayer-node/src/rpc/tests.rs
`cargo test` were sometimes failing due to concurrency issue that are covered and backed by `nextest`.
This PR fixes the issue regarding the `addr` already in used discovered by @iljakuklic
It also fixes a concurrency issue with `fail`.
Why it does not fail on the CI ?
We're using `nextest`, which is a more advance and more performant test runner. Clusterisation/concurrency are handled differently between `cargo-test` and `nextest`.
We can either enforce having both `nextest` and `cargo-test` tested on the CI or advertise that we only support nextest.
- Supporting both can be slower on a day to day as we'll have to replicate some logic provided by nextest or ignore some tests.
- Not providing `cargo-test` full support can lead users to not understand why some tests are failing.
My …
> fix: concurrency issues with fail and addr

- crates/agglayer-node/src/rpc/tests.rs
The `cargo test` command does not work out of the box due to concurrency issues. Add an assertion that checks the relevant tests are run using `nextest` with an error message that guides the users towards a resolution.
> test: Enforce RPC tests are run under nextest

- Cargo.lock
- Cargo.toml
- crates/agglayer-signer/Cargo.toml
- crates/agglayer-signer/src/lib.rs
- crates/agglayer-signer/src/tests.rs
Adding a very basic signer test of questionable value. It only checks the wallet signer for now but should be easy to extend to check GCP KMS and other signers too.
> test: add a simple signer test

- Cargo.toml
- crates/agglayer-aggregator-notifier/Cargo.toml
- crates/agglayer-node/Cargo.toml
Specify `sp1` versions in the workspace rather than individual crates. This only applies to the top-level workspace. Unfortunately, it is not straightforward to unify host-side and prover-side sp1 version given how Cargo works.
> chore: unify sp1 versions

- Cargo.lock
- crates/agglayer-config/Cargo.toml
- crates/agglayer-config/src/auth.rs
- crates/agglayer-config/src/certificate_orchestrator.rs
- crates/agglayer-config/src/certificate_orchestrator/prover.rs
- crates/agglayer-config/src/epoch.rs
- crates/agglayer-config/src/l1.rs
- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/log.rs
- crates/agglayer-config/src/outbound.rs
- crates/agglayer-config/src/rpc.rs
- crates/agglayer-config/src/shutdown.rs
- crates/agglayer-config/src/telemetry.rs
- crates/agglayer-config/tests/backward_compatibility-kurtosis.toml
- crates/agglayer-config/tests/backward_compatibility.rs
- crates/agglayer-config/tests/backward_compatibility.toml
- crates/agglayer/Cargo.toml
- crates/agglayer/src/cli.rs
- crates/agglayer/src/main.rs
- crates/agglayer/tests/config.rs
- crates/agglayer/tests/snapshots/config__config_display.snap
This PR is adding a `default` mode to the configuration, a CLI command to generate a default `config` and it switches the format from `PascalCase/lowercase` to `kebab-case`. It is related to the discussion #147 
There are backward compatibility tests in the config crate to cover most of the config used currently.
More can be added to prevent any regression, and when we're confident on the deprecation of the old format, we can clean them up.
This PR closes #83 and closes #89
> feat: adding default config and switch format

- .github/workflows/test.yml
The job that checks if the ELF is up to date doesn't work as expected in some case.
We disable it until we find a better solution
> build: disable ELF job

- .github/workflows/scripts/are_counters_progressing.sh
- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- crates/agglayer-node/Cargo.toml
- xtask/Cargo.toml
Update dependencies:
- **build(deps): bump serde_json from 1.0.121 to 1.0.122**
- **build(deps): bump clap from 4.5.11 to 4.5.13**
- **build(deps): bump which from 6.0.1 to 6.0.2**
- **build(deps): bump nu-ansi-term from 0.50.0 to 0.50.1**
- **build(deps): bump jsonrpsee from 0.24.0 to 0.24.2**
- **build(deps): bump rstest from 0.21.0 to 0.22.0**
> chore: updating dependencies 2024-08-06

- .github/workflows/cycle-tracker.yml
- .github/workflows/test.yml
This PR moves the cycle tracker test to its own dedicated workflows.
We do not need to run it often, and we shouldn't slow the PR tests with it.
The workflow is configured to be runnable manually, targeting any branch.
And it is scheduled each Wednesday at 13.
> chore: move cycle tracker to new workflow

- Cargo.lock
- crates/pessimistic-proof-test-suite/tests/local_exit_root.rs
- crates/pessimistic-proof/src/bridge_exit.rs
- crates/pessimistic-proof/src/local_state.rs
Remove the panic for the bridge messages.
If the leaf type is a message, then the non-zero `amount` corresponds to a native eth transfer
> feat: handle the native eth balance for the bridge messages

- crates/pessimistic-proof/src/keccak.rs
As noted in #234, `keccak256_combine` should only be called with fixed-size inputs (which is currently the case in the code). This PR adds a comment mentioning that in the function's doc comment so that implementers are aware.
> chore: add safety comment to `keccak256_combine`

- Cargo.lock
- crates/agglayer-node/Cargo.toml
- crates/agglayer-node/src/rpc/error.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/tests/errors.rs
- crates/agglayer-node/src/rpc/tests/mod.rs
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__dry_run.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__rollup_not_reg.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__root_bad_rollup.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__root_exit.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__root_rpc.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__root_state.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__settle_contract.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__settle_io.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__settle_receipt.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_contract.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_invalid_len.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_recov.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_signer.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_verif.snap
Introduce a mechanism to return the proper error codes from failing RPC calls and use it in the existing RPC methods. This also lays the groundwork for adding arbitrary structured data to RPC errors.
This is to make the future rate limiting errors easier to distinguish from other kinds of errors and to prepare for passing additional machine readable data in the RPC error response.
Related to:
* #219
* #213 
* Error codes returned from RPC calls have been changed from generic ones, like -20602 (invalid params) to newly introduced ones that specify the issue more precisely. Anyone relying on these error codes will have to update how they are handled. This is unlikely since the original codes were not particularly informative.
* The error message string has moved from the `data` field of the …
> feat: return proper error codes from RPC calls

- Cargo.lock
- crates/pessimistic-proof-test-suite/Cargo.toml
- crates/pessimistic-proof-test-suite/src/bin/README.md
- crates/pessimistic-proof-test-suite/src/bin/ppgen.rs
- crates/pessimistic-proof-test-suite/src/runner.rs
- crates/pessimistic-proof-test-suite/src/sample_data.rs
Add a basic utility to generate one pp based on sample data, and output the proof along with its metadata to one json file.
Generates it with the succinct infra or locally depending on the proving mode.
Relates to https://github.com/0xPolygonHermez/qa-protocol-kanban/issues/435
> feat: add pp generator

- .github/workflows/test.yml
Disable e2e tests for branches that doesn't target main
> build: prevent e2e tests for stack PR

- crates/agglayer-node/src/rpc/tests/errors.rs
This makes the test snapshot generation more stable. Was originally introduced when porting the code to `main`, to address an issue resulting from different `insta` versions. This is mainly to minimize the unnecessary differences between the two branches.
> chore: port RPC error test changes from main to v0.1.7

- Cargo.lock
- crates/agglayer-config/src/l1.rs
- crates/agglayer-config/src/l2.rs
- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/rpc.rs
- crates/agglayer-node/Cargo.toml
- crates/agglayer-node/src/kernel/mod.rs
- crates/agglayer-node/src/node.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/rpc_middleware/cancel_logger.rs
- crates/agglayer-node/src/rpc/rpc_middleware/logging_timeout.rs
- crates/agglayer-node/src/rpc/rpc_middleware/mod.rs
- crates/agglayer-node/src/rpc/rpc_middleware/tests.rs
- crates/agglayer-node/src/rpc/tests/errors.rs
- crates/agglayer/tests/snapshots/config__config_display.snap
Addresses
* #230 
* #231 
For timeouts to the L1 node requests, there was previously none, so introduce one of 45s. Contract execution should fit within 45s easily.
For timeouts to the L2 node requests, there was one of 60s. However, if the request to the agglayer node is dropped before that timeout, we do not get any useful diagnostic. So lower it to 45s as well, so we increase chances that our request to the L2 node times out before the client request to agglayer, which gives us more room to log the error. The requests to L2 nodes are rather trivial so 45s should be more than enough. This is only a partial fix / workaround, ideally cancelled requests are logged regardless of timeout.
> fix: adjust RPC timeouts

- crates/agglayer-certificate-orchestrator/src/lib.rs
- crates/agglayer-certificate-orchestrator/src/tests.rs
- crates/agglayer-certificate-orchestrator/src/tests/certifier_results.rs
This PR refactors how certifier results are handled.
> feat: adding certifier results tests

- crates/agglayer-config/src/rate_limiting.rs
- crates/agglayer/tests/snapshots/config__config_display.snap
> feat: disable `sendTx` rate limit by default

- crates/agglayer-types/src/lib.rs
- crates/pessimistic-proof/src/imported_bridge_exit.rs
Add one function to retrieve the L1 Info Tree leaf count considered for a given Certificate.
It corresponds to the highest leaf index considered among the imported bridge exits of a given Certificate.
> feat: retrieve the l1 info tree leaf count from certificate

- Cargo.lock
- Cargo.toml
- crates/agglayer-telemetry/Cargo.toml
Update dependencies that can be updated.
The following are still not straightforward:
* To update `tower`, the `jsonrpsee` crate would have to update its `tower` dep.
* To update `opentelemetry` and related packages, `opentelemetry-prometheus` has to be updated upstream to use the modified APIs.
> build: update dependencies

- crates/agglayer-config/src/epoch.rs
- crates/agglayer-config/src/l1.rs
- crates/agglayer-config/src/l2.rs
- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/outbound.rs
- crates/agglayer-config/src/prover.rs
- crates/agglayer-config/src/rate_limiting.rs
- crates/agglayer-config/src/rpc.rs
- crates/agglayer-config/src/shutdown.rs
- crates/agglayer-config/src/with/human_duration.rs
- crates/agglayer-config/src/with/mod.rs
- crates/agglayer-config/tests/snapshots/validate_deserialize__empty_rpcs.snap
- crates/agglayer/tests/snapshots/config__config_display.snap
- crates/agglayer/tests/snapshots/config__prover_config_display.snap
There is an inconsistency in time format used in the config. The rate limiter uses human readable strings like "1h" or "15min" while all other components use a plain number interpreted as seconds.
Let's address the inconsistency while improving the UX and maintaining backwards compatibility. Make the config parser to accept both human strings and number of seconds, at user discretion.
> feat: use `humantime` for `Duration` in config

- Cargo.lock
- crates/agglayer-clock/Cargo.toml
- crates/agglayer-clock/src/block.rs
- crates/agglayer-config/src/epoch.rs
- crates/agglayer-config/tests/snapshots/validate_deserialize__empty_rpcs.snap
- crates/agglayer-node/src/node.rs
- crates/agglayer-node/tests/pushing_certificate.rs
- crates/agglayer/tests/snapshots/config__config_display.snap
This PR adds and refactor how the clock behave when starting.
Basically, when started with a genesis block in the future, the clock will wait for that block number to start.
> feat: adding block clock by default

- crates/agglayer-node/src/kernel/mod.rs
- crates/agglayer-node/src/kernel/tests.rs
- crates/agglayer-node/src/zkevm_node_client.rs
No change in behavior. Just a more informative error in case zkevm node returns a `null` to a state roots query.
> fix: gracefully handle an empty repsonse from zkevm node

- Dockerfile
Add the `--platform` parameter so Docker picks up the correct architecture for the `go-builder`.
> fix: ARM build

- crates/agglayer-config/src/auth.rs
- crates/agglayer-config/tests/auth_config.rs
- crates/agglayer-config/tests/fixtures/valide_config/auth_kebab_case.toml
- crates/agglayer-config/tests/snapshots/auth_config__auth_kebab_case.snap
Fixes #413
This PR fixes an issue with the rename of the GCP KMS keys.
> fix: auth kms rename

- crates/agglayer-clock/src/block/tests.rs
The delivery order between `async` streams is not guaranteed which resulted in the test occasionally failing on `try_recv`. To fix it, we instead wait for the channel to have expected data under a timeout.
> fix: block clock test concurrency issue

- Cargo.lock
- crates/agglayer-aggregator-notifier/Cargo.toml
- crates/agglayer-aggregator-notifier/src/packer/mod.rs
- crates/agglayer-certificate-orchestrator/src/lib.rs
- crates/agglayer-certificate-orchestrator/src/network_task.rs
- crates/agglayer-types/src/lib.rs
Adding more context when Settlement contract call fails and catch it on the network task.
> feat: adding more context and error management for settlement

- crates/agglayer-node/src/epoch_synchronizer.rs
This PR prevents the agglayer epoch sync to fail when an epoch is already packed.
> fix: dont fail the sync when epoch already packed

- agglayer.toml
- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/storage.rs
- crates/agglayer-node/src/node.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/tests/get_certificate_header.rs
- crates/agglayer-node/src/rpc/tests/get_tx_status.rs
- crates/agglayer-node/src/rpc/tests/mod.rs
- crates/agglayer-node/src/rpc/tests/send_certificate.rs
- crates/agglayer-storage/src/columns/debug_certificates/mod.rs
- crates/agglayer-storage/src/columns/mod.rs
- crates/agglayer-storage/src/storage/cf_definitions.rs
- crates/agglayer-storage/src/storage/cf_definitions/debug.rs
- crates/agglayer-storage/src/storage/mod.rs
- crates/agglayer-storage/src/stores/debug.rs
- crates/agglayer-storage/src/stores/interfaces/reader.rs
- crates/agglayer-storage/src/stores/interfaces/writer.rs
- crates/agglayer-storage/src/stores/mod.rs
This PR is adding a new field in the config to activate a `debug-mode`.
The Debug mode will save all certificates received in another DB.
A new API is also exposed to retrieve them.
> feat: add a debug-mode to the node

- crates/pessimistic-proof/src/utils/smt.rs
Add method to the `Smt` struct to traverse the tree and remove all stale nodes.
> feat: smt traverse and prune

- crates/agglayer-aggregator-notifier/src/certifier/mod.rs
- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/prover.rs
- crates/agglayer-config/src/rpc.rs
- crates/agglayer-config/tests/fixtures/valide_config/grpc_max_decoding_message_size.toml
- crates/agglayer-config/tests/fixtures/valide_config/max_rpc_request_size.toml
- crates/agglayer-config/tests/fixtures/valide_config/prover_grpc_max_decoding_message_size.toml
- crates/agglayer-config/tests/snapshots/validate_deserialize__grpc_max_decoding_message_size.snap
- crates/agglayer-config/tests/snapshots/validate_deserialize__max_rpc_request_size.snap
- crates/agglayer-config/tests/snapshots/validate_deserialize__prover_grpc_max_decoding_message_size.snap
- crates/agglayer-config/tests/validate_deserialize.rs
- crates/agglayer-prover/src/prover.rs
This PR is activating the `deserialization` and the `serialization` (if not default) for max request fields of the RPC endpoint.
- `max-request-body-size` allows the configuration of the maximum request body size in bytes on the JSON-RPC API
- `max_response_body_size` allows the configuration of the maximum response body size in bytes on the JSON-RPC API
- `max-decoding-message-size`  allows the configuration of the maximum message size in bytes when decoding on the prover config
- `max-encoding-message-size`  allows the configuration of the maximum message size in bytes when encoding on the prover config
```toml
[rpc]
max-request-body-size = 104857600
[prover.grpc]
max-decoding-message-size = 104857600
```
```toml
[grpc]
max-decoding-message-size = 104857600
```
> feat: adding deserialization of max request field for rpc

- crates/agglayer-certificate-orchestrator/src/tests.rs
- crates/agglayer-node/src/epoch_synchronizer.rs
- crates/agglayer-storage/src/stores/interfaces/reader.rs
- crates/agglayer-storage/src/stores/per_epoch/mod.rs
- crates/agglayer-storage/src/stores/per_epoch/tests.rs
- crates/agglayer-storage/src/tests/mocks/per_epoch_store.rs
- crates/agglayer-storage/src/types.rs
This PR is fixing a corner case on the epoch synchronization and the opening of the latest epoch.
Fixes #466
> fix: epoch considered packed when still open

- crates/agglayer-aggregator-notifier/src/packer/mod.rs
- crates/agglayer-certificate-orchestrator/src/error.rs
- crates/agglayer-certificate-orchestrator/src/lib.rs
- crates/agglayer-certificate-orchestrator/src/network_task.rs
- crates/agglayer-certificate-orchestrator/src/tests.rs
- crates/agglayer-types/src/lib.rs
This PR is adding the notification of a failure when trying to add a certificate to the current epoch.
Fixes #467
> fix: notify network task on failure when adding the cert to epoch

- Cargo.lock
- Cargo.toml
- crates/agglayer-aggregator-notifier/Cargo.toml
- crates/agglayer-aggregator-notifier/src/packer/mod.rs
- crates/agglayer-clock/Cargo.toml
- crates/agglayer-config/src/lib.rs
- crates/agglayer-contracts/Cargo.toml
This PR checks the receipt status during the settlement of a certificate.
If the status isn't `success` the certificate is tagged as `InError`.
Fixes #471
> fix: check for receipt status during settlement of certificate

- crates/agglayer-node/src/lib.rs
- crates/agglayer-prover/src/lib.rs
This PR is adding the support of SIGTERM to both `agglayer-node` and `agglayer-prover`.
Fixes #472
> feat: adding SIGTERM signal to agglayer node and agglayer prover

- Cargo.lock
- crates/agglayer-aggregator-notifier/Cargo.toml
- crates/agglayer-aggregator-notifier/src/certifier/mod.rs
- crates/agglayer-node/Cargo.toml
- crates/agglayer-prover-types/Cargo.toml
- crates/agglayer-prover/Cargo.toml
- crates/agglayer-storage/Cargo.toml
- crates/agglayer-test-suite/Cargo.toml
- crates/agglayer-types/src/lib.rs
- crates/pessimistic-proof-test-suite/Cargo.toml
- crates/pessimistic-proof-test-suite/src/bin/convertor.rs
- crates/pessimistic-proof-test-suite/src/bin/ppgen.rs
- crates/pessimistic-proof-test-suite/src/event_data.rs
- crates/pessimistic-proof-test-suite/src/forest.rs
- crates/pessimistic-proof-test-suite/src/sample_data.rs
- crates/pessimistic-proof-test-suite/tests/e2e_local_pp.rs
Exported `agglayer_primitives` through `agglayer_types::primitives`. 
A bit of cleanup of Cargo.toml files.
Fixes #504
> chore: agglayer primitives export

- Cargo.lock
- crates/agglayer-certificate-orchestrator/src/tests.rs
- crates/agglayer-node/src/lib.rs
- crates/agglayer-prover/src/lib.rs
- crates/agglayer/Cargo.toml
- crates/agglayer/build.rs
- crates/agglayer/src/cli.rs
- crates/agglayer/src/main.rs
- tests/integrations/src/agglayer_setup.rs
Adds detailed version info cli command and prints version info on startup of node and prover.
It looks like this:
```
$ cargo run -- --version  
$ cargo run -- -V
agglayer agglayer (v0.2.0-rc.20-20-g7c3e48d-dirty) [git commit timestamp: 2025-01-08T18:13:56.000000000Z]
```
> feat: add version info

- Cargo.lock
- crates/agglayer-certificate-orchestrator/src/network_task/tests.rs
- crates/agglayer-certificate-orchestrator/src/network_task/tests/status.rs
- crates/pessimistic-proof-test-suite/Cargo.toml
- crates/pessimistic-proof-test-suite/src/event_data.rs
- crates/pessimistic-proof-test-suite/src/forest.rs
- crates/pessimistic-proof-test-suite/src/sample_data.rs
- crates/pessimistic-proof-test-suite/tests/cycle-tracker.rs
- crates/pessimistic-proof-test-suite/tests/e2e_local_pp.rs
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s00_be000.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be000.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be001.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be002.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be020.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be050.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be100.snap
- crates/pessimistic-proof-test-suite/tests/snapshots/cycle_tracker__s01_be223.snap
- crates/pessimistic-proof/src/bridge_exit.rs
A bunch of improvements to the cycle tracker that came up during the removal of the sp1 patch hack.
* Make the cycle tracker inputs and outputs deterministic
* Record cycle execution stats in a snapshot
* This allows us to observe perf changes. Can be reverted if deemed too annoying.
* Enable cycle tracker by default (it's not actually that slow)
* A number of minor refactors
Related:
* changes prompted by #438
* related #143
> test: cycle tracker improvements

- Cargo.lock
- crates/agglayer-aggregator-notifier/src/certifier/mod.rs
- crates/agglayer-aggregator-notifier/src/certifier/tests.rs
- crates/agglayer-aggregator-notifier/src/packer/tests.rs
- crates/agglayer-contracts/Cargo.toml
- crates/agglayer-contracts/src/lib.rs
- crates/agglayer-types/src/lib.rs
- Check that the L1 Info Root / leaf count referred by the Certificate exists on the latest L1 block, reject otherwise
- Await the certifier process until that the referred L1 Info Root is referred in a finalized block
If the L1 ends up doing a reorg leading to the referred L1 info tree entry to be non-existent, then the Certificate will become `InError` with the error `CertificationError::L1InfoRootNotFound`.
Fixes #479
> feat: await for the l1 info tree entry to be finalized

- Cargo.lock
- Cargo.toml
- crates/agglayer-node/Cargo.toml
- crates/agglayer-primitives/Cargo.toml
- crates/agglayer-storage/Cargo.toml
- crates/agglayer-telemetry/Cargo.toml
- crates/agglayer-telemetry/src/lib.rs
- crates/pessimistic-proof-core/Cargo.toml
- crates/pessimistic-proof-test-suite/Cargo.toml
- tests/integrations/Cargo.toml
Take over https://github.com/agglayer/agglayer/pull/527. Includes bumping axum to 0.8.
Changelog review:
- All changelog entries look reasonably harmless
- RocksDB 0.22 -> 0.23 will lead to the rocksdb 8 -> 9 major version bump. This [should be harmless](https://github.com/facebook/rocksdb/wiki/RocksDB-Compatibility-Between-Different-Releases), but it may mean that we could have difficulty rolling back this upgrade in production (though in theory we shouldn’t). However, we definitely don’t want to stay on rocksdb 8 forever, so let’s just upgrade.
Fixes #527
In theory (according to its doc), bumping rocksdb from 8 to 9 should not be a breaking change. However it’s still a major upgrade, so I’m writing it out here for full clarity.
> build(deps): bump deps

- crates/agglayer-node/src/kernel/mod.rs
- crates/agglayer-node/src/lib.rs
- crates/agglayer-node/src/node.rs
- crates/agglayer-node/src/rpc/error.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/tests/errors.rs
- crates/agglayer-node/src/rpc/tests/get_tx_status.rs
- crates/agglayer-node/src/rpc/tests/mod.rs
- crates/agglayer-node/src/rpc/tests/send_certificate.rs
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__cert_notfound.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__dry_run_rollup_man.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__txstatus_check.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__txstatus_notfound.snap
- crates/agglayer-node/src/service/error.rs
- crates/agglayer-node/src/service/mod.rs
Move the logic from rpc implementation into a separate component, Agglayer service. This will allow it to be reused when introducing new external interfaces, initially gRPC.
* fixes #544
> refactor: move logic from rpc to a separate component

- crates/agglayer-node/src/kernel/mod.rs
- crates/agglayer-node/src/kernel/tests.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/tests/errors.rs
- crates/agglayer-node/src/rpc/tests/mod.rs
- crates/agglayer-node/src/rpc/tests/send_certificate.rs
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__cert_sig.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_invalid_len.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_recov.snap
- crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_verif.snap
- crates/agglayer-types/src/lib.rs
Validate certificates’ claimed emitter. This does not verify any new additional signature, and renames functions accordingly.
Also, swap the order of pending & state saves to database. I’m not entirely sure why this is required, as I’m not familiar enough with the database yet. Still, did as the task requested.
Fixes https://github.com/agglayer/agglayer/issues/553
Replaces https://github.com/agglayer/agglayer/pull/557 ; handles review comments and adds metrics for certificate signature verifications (with a separate label)
> feat: confirm certificates’ claimed emitter is allowed to emit

- crates/agglayer-config/src/storage/backup.rs
- crates/agglayer-config/tests/snapshots/backup__backup_enabled.snap
This PR is fixing the format of the backup config, switching from `snake_case` to `kebab-case`.
> fix: fixing backup config format

- crates/agglayer-node/src/rpc/admin.rs
- crates/agglayer-node/src/rpc/mod.rs
- crates/agglayer-node/src/rpc/tests/get_latest_known_certificate_header.rs
This PR allows an admin to update the latest proven certificate and latest pending certificate.
It also includes a little fix on the ordering of `latestKnownCertificate` when all value are the same, we prioritize the settled one.
> fix: adding set latest proven/pending method on admin RPC

- Cargo.lock
Incidentally, this should fix the recent security audit CI failures.
> fix(security): bump openssl to non-vulnerable version

- .github/workflows/coverage.yml
- .github/workflows/mq-test.yml
- .github/workflows/pr-quality.yml
- .github/workflows/pr-test.yml
Required jobs needs to be both on `merge_queue` and `pull_request`.
> build: update required job on merge_queue

- Dockerfile
Before this change, each code change triggers a re-download of the SP1 circuits. After this change, a code change will only re-run `cargo build`. On my machine and network, with a small change, this brings the docker rebuild time down from 90s to 30s.
> feat: make docker image rebuilds 3x as fast

- .github/workflows/coverage.yml
This PR removes the sonarcloud action from the CI to rely on automatic mode.
> build: remove sonarcloud job to rely on automode

- .github/workflows/proto.yml
Fixes the ref+branch used when triggered in merge_group.
> fix: github action proto ref for merge_group

- .github/dependabot.yml
This reverts commit e241619aa1a434d1deae0e00ca491036cbbe5014.
Sadly, dependabot started failing with "unknown error" since this was merged.
> revert: make dependabot update prover packages in one PR (#680)

- crates/agglayer-config/src/lib.rs
- crates/agglayer-config/src/rpc.rs
- crates/agglayer-config/tests/snapshots/auth_config__auth_kebab_case.snap
- crates/agglayer-config/tests/snapshots/backup__backup_enabled.snap
- crates/agglayer-config/tests/snapshots/validate_deserialize__empty_rpcs.snap
- crates/agglayer-config/tests/snapshots/validate_deserialize__grpc_max_decoding_message_size.snap
- crates/agglayer-config/tests/snapshots/validate_deserialize__max_rpc_request_size.snap
- crates/agglayer-jsonrpc-api/src/tests/get_tx_status.rs
- crates/agglayer-jsonrpc-api/src/tests/send_certificate.rs
- crates/agglayer-jsonrpc-api/src/testutils.rs
- crates/agglayer-node/src/node.rs
- crates/agglayer/tests/snapshots/config__config_display.snap
- tests/integrations/src/agglayer_setup.rs
See https://stackoverflow.com/questions/40410392/grpc-endpoint-with-non-root-path In particular, the go library seems to not support prefixing calls with `/grpc`.
cc @goran-ethernal as you handled the go part of this investigation
cc @Freyskeyd as you wrote the initial code
Part of #666
> fix: grpc always expects to be on the domain root

- tests/integrations/src/agglayer_setup.rs
The macro otherwise breaks if used from a module where the correct `Duration` is not imported.
> fix: use absolute path in a macro

- .github/dependabot.yml
Three groups have been introduced:
* `provers` for keeping up to date with the `agglayer/provers` repo
* `sp1` for which we have a different update policy from other external dependencies, and updating it often fails, making dependabot PRs way less useful
* `external`, previously called `all`, for the remaining external dependencies. Major version updates still get separate PRs.
Looking at the dependabot logs, the failures we've seen may not have been a result of #680 (reverted #685), so I think this calls for another attempt. I have also changed the indentation a bit to be in line with most yaml syntax examples online, and possibly friendlier to parsers.
> build: more granular dependabot groups, take 2

- .github/workflows/doc.yml
- .github/workflows/quality.yml
- Makefile.ci.toml
Attempt to resolve the recent CI failures on an `sp1`-related package with nightly toolchain.
> ci: use stable toolchain for `doc` and `clippy`

- .github/workflows/test.yml
This PR update the github workflow to prevent non reportable job result when using reusable workflows.
> build: update e2e flow to be used as required step

- .github/workflows/docker-build.yml
- .github/workflows/test.yml
Here are some CI updates. There are two changes, pretty much independent of each other. We can pick which we want.
I am not able to test them properly. Running the workflow manually on this branch runs into an image upload permission issue. Running it manually on main works but that does not include the changes from this PR.
> ci: push docker images when updaing `main`

- .github/dependabot.yml
Some recent developments, such as addition of the `interop` repo, have caused the dependabot group definitions to be no longer a good match. Here are some improvements.
* The `provers` group becomes `agglayer` group, containing updates from both the `provers` repo and the `interop` repo.
* Generalized and updated some patterns to match the new crate names.
* Fixed a typo in a pattern.
> build: improve dependabot grouping

- crates/agglayer-grpc-api/src/certificate_submission_service/mod.rs
To avoid dumping a lot of info in logs, this PR is removing the `request` from the `span`.
> fix: update instrumentation to skip request in submit_certificate

- crates/agglayer-aggregator-notifier/src/certifier/mod.rs
- crates/agglayer-types/src/lib.rs
This PR is adding the `l1_info_root` check during the certification.
> feat: add handling for l1_info_root without imported bridge exits

- Dockerfile
Upgrade docker images from bullseye-based to bookworm-based.
Just changed [Dockerfile](https://github.com/agglayer/agglayer/blob/build/bookworm/Dockerfile)
> feat: switch to bookworm based docker images

- crates/agglayer-types/src/lib.rs
Intermediate solution prior to having a mandatory l1 info tree leaf count introduced by #768
> feat: use provided l1 info tree leaf count first

- crates/agglayer-certificate-orchestrator/src/certificate_task.rs
- crates/agglayer-certificate-orchestrator/src/network_task.rs
Handle delayed https://github.com/agglayer/agglayer/pull/819#discussion_r2124732959
Also trace all messages sent to network task, as it could always be useful
> chore: introduce send_to_network_task helper

- crates/agglayer-aggregator-notifier/src/certifier/tests.rs
- crates/agglayer-aggregator-notifier/src/settlement_client/rpc.rs
- crates/agglayer-aggregator-notifier/src/settlement_client/tests.rs
- crates/agglayer-contracts/src/aggchain.rs
- crates/agglayer-contracts/src/rollup.rs
A small clean up of contract and settlement generics, consisting of two changes:
* Remove unused associated types in contract traits
* Make `submit_certificate_settlement` and `wait_for_settlement` into standalone methods (called from the original trait implementation). That allows for relaxing some generic bounds on the type parameters, hopefully allowing for simpler testing / mocking setup when only one of these methods needs to be tested.
> refactor: clean up contract generics

- Cargo.lock
- crates/agglayer-jsonrpc-api/src/kernel/mod.rs
- crates/agglayer-jsonrpc-api/src/kernel/tests.rs
- crates/agglayer-rpc/src/error.rs
- crates/agglayer-rpc/src/lib.rs
- crates/agglayer-storage/src/stores/state/tests.rs
- crates/agglayer-types/Cargo.toml
- crates/agglayer-types/src/certificate/mod.rs
- crates/agglayer-types/src/certificate/testutils.rs
- crates/agglayer-types/src/error.rs
- crates/pessimistic-proof-test-suite/src/bin/ppgen.rs
- crates/pessimistic-proof-test-suite/src/forest.rs
- crates/pessimistic-proof-test-suite/tests/cycle-tracker.rs
- crates/pessimistic-proof-test-suite/tests/e2e_local_pp.rs
Follow up of the first iteration done with #882 
- Update the extra signature commitment on the certificate id and the l1 info tree leaf count
- Adapt the verification of the PP signature to accept either a V2 or a V3 commitment
- Note that the verification on whether the version is the expected one as per what is settled in the L1 is only done at the witness generation step
- Adapt the tests
> feat: update extra signature and adapt commitment versions

- crates/agglayer-clock/src/block.rs
- crates/agglayer-clock/src/block/tests.rs
> fix: skipped L1 blocks should not tear down the node [v0.3.3]

- crates/agglayer-contracts/src/lib.rs
- crates/agglayer-contracts/src/rollup.rs
If rollup contract is not set in the rollup data (e.g. for non existing chain), return proper error.
Fixes [2025-05#31](https://github.com/agglayer/security/issues/141)
> fix: zero rollup contract error

- crates/agglayer-storage/src/columns/certificate_per_network/mod.rs
- crates/agglayer-storage/src/columns/latest_pending_certificate_per_network/mod.rs
- crates/agglayer-storage/src/columns/latest_proven_certificate_per_network/mod.rs
- crates/agglayer-storage/src/columns/latest_settled_certificate_per_network/mod.rs
- crates/agglayer-storage/src/columns/local_exit_tree_per_network/mod.rs
- crates/agglayer-storage/src/columns/mod.rs
- crates/agglayer-storage/src/columns/pending_queue/mod.rs
- crates/agglayer-storage/src/lib.rs
- crates/agglayer-storage/src/types/certificate/mod.rs
- crates/agglayer-storage/src/types/mod.rs
With the gradual move towards protobuf in storage, the requirement for all storage types to implement the `serde` traits is unnecessary and a bit limiting. This removes the `serde` supertraits from `agglayer_storage::columns::Codec`. Consequently, we do not have convenient default implementation for the methods so a macro is introduced for it.
> chore: remove `serde` requirement from storage codec

- crates/agglayer-storage/src/storage/mod.rs
* The options were not previously passed to the batch write method.
* Also a small refactor to get the column family easier.
* Fixes agglayer/security#104.
> fix: use `DB::default_write_options` consistently

- crates/agglayer-aggregator-notifier/src/lib.rs
- crates/agglayer-aggregator-notifier/src/proof.rs
This is removing an unused struct `Proof`
> fix: remove unused Proof

- crates/agglayer-storage/src/stores/state/network_info/mod.rs
- crates/agglayer-storage/src/stores/state/tests.rs
This PR removes the throw of an error and replace it by the expected default value if the value is not found.
> fix: network info retrieval
