agglayer/agglayer

.github/workflows/doc.yml
Fixes the GitHub actions doc generation.
=> chore: updating github pages actions

Cargo.lock, crates/agglayer-telemetry/Cargo.toml
Update `opentelemetry` crates.
=> chore: update opentelemetry crates

.github/CODEOWNERS
Updates the `CODEOWNERS` file for better control over the reviewers.
=> chore: updating CODEOWNERS

.github/workflows/coverage.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml, crates/agglayer-clock/Cargo.toml, crates/agglayer-clock/src/block.rs, crates/agglayer-clock/src/lib.rs, crates/agglayer-clock/src/time.rs
This clock implementation will listen on L1 block production in order to provide `EpochEnded` event.
=> feat(clock): implement Block clock

crates/agglayer-config/src/auth.rs, crates/agglayer-gcp-kms/src/lib.rs
This PR backports the different fixes of `0.1.0` into `main`:
- #90
=> fix(config): add version and update kms parsing [backport]

sonar-project.properties
chore: update sonar-project.properties
Updating sonar.properties to update Github Organization
=> chore: update sonar-project.properties

Cargo.lock, Cargo.toml, crates/agglayer-node/Cargo.toml, crates/agglayer-node/src/rpc/mod.rs, crates/agglayer-node/src/rpc/tests.rs
This PR is updating `jsonrpsee` and related crates that were locked by it.
=> feat: updating jsonrpsee / tower-http / hyper

README.md, crates/agglayer-clock/src/time.rs, sonar-project.properties
This PR updates the different links and docs regarding the organisation/repo rename.
=> chore: update after rename

crates/agglayer-node/src/rpc/mod.rs
Remove leftover log on `service_health`
=> chore: remove leftover 0.1.1

.github/dependabot.yml
Update dependabot config to run on a weekly basis.
=> build: update dependabot schedule timing

Cargo.lock, crates/agglayer-certificate-orchestrator/src/lib.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-node/Cargo.toml, crates/agglayer-node/src/node/notifier.rs, crates/agglayer-node/src/rpc/mod.rs, crates/agglayer-node/src/rpc/tests.rs, crates/pessimistic-proof/src/proof.rs, crates/pessimistic-proof/tests/full_proof.rs
This PR updates the `send_certificate` RPC to use `Certificate`
=> feat: update send_certificate rpc type

crates/agglayer-node/src/rpc/mod.rs
Improve logs to have the full hash and not just a truncated one
=> chore: improve logs

crates/agglayer-node/src/rpc/mod.rs
This PR backports changes for `v0.1.3`
=> chore: backport release 0.1.3

.github/workflows/quality.yml
This PR updates `cargo audit` permissions
=> chore: updating cargo audit permissions

.github/workflows/coverage.yml, .github/workflows/quality.yml, .github/workflows/test.yml
This PR adds a check for the ELF file status based on changes of the `pessimistic-proof` related crates.
=> chore: adding jobs to check ELF

Cargo.lock, Cargo.toml, crates/agglayer-node/Cargo.toml
This PR is updating the deps that Dependabot updated.
=> chore: updating cargo dependencies

crates/agglayer-config/src/lib.rs, crates/agglayer-config/src/proof_signers.rs, crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/kernel/tests.rs
This PR adds the `ProofSigner` config which allow a CDK to define an alternative signer to the `SignedTx`
=> feat: adding ProofSigner config and behavior

crates/agglayer-node/src/kernel/tests.rs, crates/agglayer-node/src/rpc/mod.rs
This PR adds more logs context in case of errors.
=> fix: adding more context to logs

.cargo/config.toml, .github/workflows/coverage.yml, Cargo.lock, Cargo.toml, crates/agglayer-aggregator-notifier/Cargo.toml, crates/agglayer-aggregator-notifier/src/lib.rs, crates/agglayer-aggregator-notifier/src/tests/mod.rs
This PR adds some RUSTFLAGS for coverage execution.
=> build: reduce coverage time

Cargo.lock, crates/agglayer-node/Cargo.toml, crates/agglayer-node/build.rs, crates/agglayer-node/src/contracts/mod.rs, crates/agglayer-node/src/contracts/polygon_rollup_manager.rs, crates/agglayer-node/src/contracts/polygon_zk_evm.rs, crates/agglayer-node/src/rpc/mod.rs
This PR adds and refactor a little bit the RPC error handling
=> chore: refactor logs for error rpc

crates/agglayer-config/src/auth.rs, crates/agglayer-config/src/l1.rs, crates/agglayer-config/src/lib.rs, crates/agglayer-config/src/telemetry.rs, crates/agglayer/tests/snapshots/config__config_display.snap
Some were previously missed.
Related:
* #151 
* #147 
* #83
=> fix: convert the remaining config keys to `kebab-case`

crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/node.rs
To prevent `nonce` concurrency error, we introduce a new middleware on the `Provider`, the `NonceManagerMiddleware`.
=> feat: adding nonce-manager

.github/workflows/coverage.yml, .github/workflows/test.yml, Cargo.lock, Cargo.toml
Reactivate e2e tests job and fix `sp1up` setup broke due to [this](https://github.com/succinctlabs/sp1/pull/1109)
=> chore: reactivate e2e tests

Cargo.lock, Cargo.toml, crates/agglayer-aggregator-notifier/Cargo.toml, crates/agglayer-aggregator-notifier/src/sp1/mod.rs, crates/agglayer-certificate-orchestrator/Cargo.toml, crates/agglayer-config/Cargo.toml, crates/agglayer-gcp-kms/Cargo.toml, crates/agglayer-node/Cargo.toml, crates/agglayer-signer/Cargo.toml, crates/agglayer-telemetry/Cargo.toml, crates/agglayer-telemetry/src/lib.rs, crates/agglayer/Cargo.toml, crates/pessimistic-proof-program/Cargo.lock, crates/pessimistic-proof-program/Cargo.toml, crates/pessimistic-proof/Cargo.toml
Remove unused dependencies and update others.
=> chore: update dependencies 2024-07-23

crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/node.rs, crates/agglayer-node/src/rpc/mod.rs
This PR backports changes made on the `v0.1.6` release:
- #182
- Logs update
=> chore: backport changes made for 0.1.6

Cargo.lock, crates/pessimistic-proof-program/Cargo.lock, crates/pessimistic-proof-utils/src/local_exit_tree.rs
`Cargo.lock` got corrupted when merging #163 and #164. This should fix it
=> fix: fix lock file

.github/workflows/test.yml, Cargo.lock, crates/agglayer-node/Cargo.toml, crates/agglayer-node/build.rs, crates/agglayer-node/src/contracts/mod.rs, crates/agglayer-node/src/contracts/polygon_rollup_manager.rs, crates/agglayer-node/src/contracts/polygon_zk_evm.rs, crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/node.rs, crates/agglayer-node/src/rpc/mod.rs
Backport changes made for `v0.1.5` into main:
- #170
=> chore: backport changes made for 0.1.5

.github/workflows/scripts/are_counters_progressing.sh, .github/workflows/test.yml
Remove logs and fix test workflow
=> chore: fixing test workflow

crates/pessimistic-proof/src/bridge_exit.rs, crates/pessimistic-proof/src/local_state.rs, crates/pessimistic-proof/src/proof.rs
@invocamanman pointed out a few missing checks in the PP.
=> fix: missing checks in pp

Cargo.lock, Cargo.toml
This PR updates the different lib related to agglayer.
=> chore: update deps 2024-09-02

Cargo.lock, crates/agglayer-storage/Cargo.toml, crates/agglayer-storage/src/lib.rs
This PR adds the storage crate to the repository.
It is a barebone crate which contains nothing more that the structure of the different component of the storage.
It is divided into:
- `columns` which contains the column definition and the different `codec` to serialize the data
- `storage` which contains the `rocksdb` abstraction (physical storage)
- `stores` which contains the store implementation to interact with the physical storage (logical stores)
=> feat: adding storage crate

Cargo.lock, crates/agglayer-storage/Cargo.toml, crates/agglayer-storage/src/columns/balance_tree_per_network/mod.rs, crates/agglayer-storage/src/columns/balance_tree_per_network/tests.rs, crates/agglayer-storage/src/columns/certificate_header/mod.rs, crates/agglayer-storage/src/columns/certificate_header/tests.rs, crates/agglayer-storage/src/columns/certificate_per_network/mod.rs, crates/agglayer-storage/src/columns/certificate_per_network/tests.rs, crates/agglayer-storage/src/columns/epochs/certificates/mod.rs, crates/agglayer-storage/src/columns/epochs/metadata/mod.rs, crates/agglayer-storage/src/columns/epochs/proofs/mod.rs, crates/agglayer-storage/src/columns/latest_certificate_per_network/mod.rs, crates/agglayer-storage/src/columns/latest_certificate_per_network/tests.rs, crates/agglayer-storage/src/columns/local_exit_tree_per_network/mod.rs, crates/agglayer-storage/src/columns/metadata/mod.rs, crates/agglayer-storage/src/columns/mod.rs, crates/agglayer-storage/src/columns/nullifier_tree_per_network/mod.rs, crates/agglayer-storage/src/columns/nullifier_tree_per_network/tests.rs, crates/agglayer-storage/src/columns/pending_queue/mod.rs, crates/agglayer-storage/src/columns/proof_per_certificate/mod.rs, crates/agglayer-storage/src/columns/proof_per_certificate/tests.rs, crates/agglayer-storage/src/error.rs, crates/agglayer-storage/src/types.rs
This PR adds the different columns to the storage crate.
=> feat: adding columns to storage

.github/workflows/test.yml
E2E tests are disabled due to miss configuration in the test actions.
=> fix: fixing github action e2e

.github/workflows/test.yml, Cargo.lock, Dockerfile, crates/agglayer-storage/Cargo.toml, crates/agglayer-storage/src/error.rs, crates/agglayer-storage/src/storage/iterators/mod.rs, crates/agglayer-storage/src/storage/mod.rs, crates/agglayer-storage/src/tests.rs
This PR adds the physical storage structs based on `rocksdb` to the `agglayer-storage` crate.
=> feat: adding physical storage

.github/workflows/test.yml, Cargo.lock, Dockerfile, crates/agglayer-storage/Cargo.toml, crates/agglayer-storage/benches/latest_certificate_bench.rs, crates/agglayer-storage/src/error.rs, crates/agglayer-storage/src/storage/iterators/mod.rs, crates/agglayer-storage/src/storage/mod.rs, crates/agglayer-storage/src/stores/interfaces.rs, crates/agglayer-storage/src/stores/interfaces/reader.rs, crates/agglayer-storage/src/stores/interfaces/writer.rs, crates/agglayer-storage/src/stores/metadata/mod.rs, crates/agglayer-storage/src/stores/metadata/tests.rs, crates/agglayer-storage/src/stores/mod.rs, crates/agglayer-storage/src/stores/pending/mod.rs, crates/agglayer-storage/src/stores/per_epoch/mod.rs, crates/agglayer-storage/src/stores/state/mod.rs, crates/agglayer-storage/src/stores/state/tests.rs, crates/agglayer-storage/src/tests.rs, crates/agglayer-storage/src/types.rs
This PR adds the logical stores to interact with the storages.
=> feat: adding logical stores

crates/agglayer-node/src/rpc/rpc_middleware/tests.rs
The tests occasionally fail. The likely reason is that tokio simulated time (used for testing) does not play nicely with actions that can take real time. An example of such an action is a HTTP request to an RPC server. While both the client and the server both live in the same process, the request is still routed through syscalls. The suspension of a task by syscall makes tokio advance time before it was intended.
This changes the tests to use wall clock time instead. The timeouts have been shortened to keep the test running time at a reasonable level. No test should take any more than just over 3 seconds. While it's not much, it will still limit the amount of parallelism available to other testing tasks to some degree.
* #259 
* #230 
* #231
=> fix: use real time in RPC middleware tests

Cargo.lock, Cargo.toml, crates/agglayer-storage/Cargo.toml, crates/agglayer-storage/benches/latest_certificate_bench.rs, crates/agglayer-storage/src/columns/balance_tree_per_network/mod.rs, crates/agglayer-storage/src/columns/balance_tree_per_network/tests.rs, crates/agglayer-storage/src/columns/certificate_header/mod.rs, crates/agglayer-storage/src/columns/certificate_header/tests.rs, crates/agglayer-storage/src/columns/certificate_per_network/mod.rs, crates/agglayer-storage/src/columns/certificate_per_network/tests.rs, crates/agglayer-storage/src/columns/epochs/certificates/mod.rs, crates/agglayer-storage/src/columns/epochs/proofs/mod.rs, crates/agglayer-storage/src/columns/nullifier_tree_per_network/mod.rs, crates/agglayer-storage/src/columns/nullifier_tree_per_network/tests.rs, crates/agglayer-storage/src/columns/proof_per_certificate/tests.rs, crates/agglayer-storage/src/error.rs, crates/agglayer-storage/src/lib.rs, crates/agglayer-storage/src/storage/iterators/mod.rs, crates/agglayer-storage/src/storage/mod.rs, crates/agglayer-storage/src/stores/epochs.rs, crates/agglayer-storage/src/stores/interfaces/reader.rs, crates/agglayer-storage/src/stores/interfaces/writer.rs, crates/agglayer-storage/src/stores/mod.rs, crates/agglayer-storage/src/stores/pending/mod.rs, crates/agglayer-storage/src/stores/per_epoch/mod.rs, crates/agglayer-storage/src/stores/state/mod.rs, crates/agglayer-storage/src/tests.rs, crates/agglayer-storage/src/types.rs, crates/agglayer-types/src/lib.rs
This PR adds methods to the stores to interact with the physical storage.
=> feat: adding methods to stores

.github/workflows/coverage.yml, .github/workflows/doc.yml, .github/workflows/quality.yml, .github/workflows/test.yml, .github/workflows/test:e2e.yml, Makefile.ci.toml, Makefile.toml, crates/agglayer-storage/src/storage/mod.rs, crates/pessimistic-proof-test-suite/src/forest.rs
This PR adds `cargo-make` and update some github workflows.
=> build: updating github build

.github/workflows/test.yml, .github/workflows/test:e2e.yml
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Bump to kurtosis-cdk `v0.2.11`
- Update the RPC URL to check erigon's RPC
- The agglayer service name has been renamed also
Fixes # (issue)
Please explain in detail, if applicable, which changes you performed in the PR and link them to issues. (If not applicable you can remove this whole section)
Please explain in detail which changes are breaking changes in the PR. (If not applicable you can remove this whole section)
=> ci: bump kurtosis cdk version

crates/pessimistic-proof/src/local_exit_tree/data.rs, crates/pessimistic-proof/src/utils/smt.rs
Minor bound checks in SMT/LET methods spotted in the audit.
=> fix: add minor bound checks

.cargo/audit.toml, Cargo.lock, Cargo.toml, crates/agglayer-prover/Cargo.toml
* Update `tonic`
* Ignore `RUSTSEC-2024-0376`, please see the code comment for explanation.
=> build: update `tonic` and ignore an irrelevant advisory

.github/workflows/quality.yml, Cargo.lock, Cargo.toml, crates/agglayer-node/Cargo.toml, crates/agglayer-prover-types/Cargo.toml, crates/agglayer-prover-types/build.rs, crates/agglayer-prover-types/src/generated/agglayer.prover.v1.rs, crates/agglayer-storage/Cargo.toml
Update dependencies.
Does not include update of `opentelemetry` (`0.24.0` -> `0.25.0`) since it is more involved than a simple version bump.
Includes some minor cleanup of package feature specifications.
=> build: update dependencies

.github/workflows/test:e2e.yml
This PR activates the push of docker image for workflow_dispatch.
=> build: activate docker build for workflow_dispatch

crates/agglayer-types/src/lib.rs, crates/pessimistic-proof/src/global_index.rs, crates/pessimistic-proof/src/imported_bridge_exit.rs, crates/pessimistic-proof/src/local_state.rs, crates/pessimistic-proof/src/multi_batch_header.rs, crates/pessimistic-proof/src/proof.rs
- add more errors and propagate relevant context with them
- add more rustdoc on errors
=> feat: extend errors and their doc around certificate

crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-certificate-orchestrator/src/tests/certifier_results.rs, crates/agglayer-node/src/node.rs, crates/agglayer-storage/src/stores/epochs.rs, crates/agglayer-storage/src/stores/interfaces/writer.rs, crates/agglayer-storage/src/stores/pending/mod.rs, crates/agglayer-storage/src/stores/per_epoch/mod.rs, crates/agglayer-storage/src/stores/per_epoch/tests.rs, crates/agglayer-storage/src/stores/state/mod.rs, crates/agglayer-storage/src/tests/mocks/per_epoch_store.rs
This PR adds tests to the `add_certificate` methods of the `PerEpoch` store.
=> test: adding tests on the add_certificate

crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-certificate-orchestrator/src/tests/certifier_results.rs, crates/agglayer-certificate-orchestrator/src/tests/receive_certificates.rs, crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__get_certificate_header__get_certificate_header::found.snap, crates/agglayer-storage/src/columns/certificate_header/tests.rs, crates/agglayer-storage/src/columns/certificate_per_network/tests.rs, crates/agglayer-storage/src/columns/mod.rs, crates/agglayer-storage/src/stores/state/mod.rs, crates/agglayer-types/src/lib.rs, crates/pessimistic-proof-test-suite/src/forest.rs
Adding one metadata field in the certificate for chain purposes
Fixes #377
=> feat: add metadata field in the certificate

Cargo.lock, Cargo.toml, crates/agglayer-aggregator-notifier/Cargo.toml, crates/agglayer-contracts/Cargo.toml, crates/agglayer-prover/src/executor.rs, crates/agglayer-types/Cargo.toml, crates/agglayer-types/src/lib.rs, crates/pessimistic-proof-test-suite/Cargo.toml, crates/pessimistic-proof-test-suite/src/runner.rs, crates/pessimistic-proof/Cargo.toml
Simply upgrading sp1 deps to v3.0.0 as agreed so that we launch with the latest available version as of today
=> chore: upgrade sp1 to v3.0.0

.github/workflows/test:e2e.yml
To better control how we want to update kurtosis, this PR is fixing the version that we use.
=> build: fixing kurtosis version

.github/workflows/quality.yml, Makefile.ci.toml, crates/agglayer-certificate-orchestrator/src/lib.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-config/src/lib.rs, crates/agglayer-config/src/rate_limiting.rs, crates/agglayer-storage/src/storage/iterators/mod.rs, crates/pessimistic-proof-test-suite/src/bin/ppgen.rs, crates/pessimistic-proof-test-suite/src/sample_data.rs, crates/pessimistic-proof/src/imported_bridge_exit.rs, crates/pessimistic-proof/src/local_exit_tree/data.rs
This PR is reactivating clippy as the new version is fixed.
=> test: reactivating clippy

.github/workflows/quality.yml
Update the timeout of the clippy job
=> build: update the timeout of clippy

crates/agglayer-node/src/rate_limiting/local/limiter/mod.rs
* fixes https://github.com/agglayer/security/issues/23
=> fix: avoid panic in rate limiter in release mode

Cargo.lock, Cargo.toml, crates/agglayer-certificate-orchestrator/Cargo.toml, crates/agglayer-certificate-orchestrator/src/lib.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-node/Cargo.toml, crates/agglayer-node/src/lib.rs, crates/agglayer-node/src/node.rs, crates/agglayer-prover/Cargo.toml, crates/agglayer-prover/src/lib.rs, crates/agglayer-prover/src/prover.rs, crates/agglayer-telemetry/Cargo.toml, crates/agglayer-telemetry/src/lib.rs
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please explain in detail, if applicable, which changes you performed in the PR and link them to issues. (If not applicable you can remove this whole section)
Please explain in detail which changes are breaking changes in the PR. (If not applicable you can remove this whole section)
=> refactor!: remove #[buildstructor]

crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-aggregator-notifier/src/certifier/tests.rs, crates/agglayer-certificate-orchestrator/src/error.rs, crates/agglayer-certificate-orchestrator/src/network_task.rs, crates/agglayer-config/src/l1.rs, crates/agglayer-config/tests/snapshots/auth_config__auth_kebab_case.snap, crates/agglayer-config/tests/snapshots/validate_deserialize__empty_rpcs.snap, crates/agglayer-contracts/build.rs, crates/agglayer-contracts/src/lib.rs, crates/agglayer-contracts/src/polygon_zkevm_global_exit_root_v2.rs, crates/agglayer-contracts/src/polygonzkevmglobalexitrootv2.json, crates/agglayer-node/src/node.rs, crates/agglayer-prover/src/executor/tests.rs, crates/agglayer-types/src/lib.rs, crates/agglayer/tests/snapshots/config__config_display.snap, crates/pessimistic-proof-test-suite/src/bin/ppgen.rs, crates/pessimistic-proof-test-suite/tests/cycle-tracker.rs, crates/pessimistic-proof-test-suite/tests/e2e_local_pp.rs
This PR backports and fix some tests regarding the leafcount calculation.
=> fix: backport leafcount fixes

Cargo.lock, crates/agglayer-aggregator-notifier/Cargo.toml, crates/agglayer-aggregator-notifier/src/packer/mod.rs, crates/agglayer-aggregator-notifier/src/packer/tests.rs
This PR is adding some more context in the settlement transactions
=> feat: adding logs to settlement

.gitignore, crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-node/src/rpc/mod.rs, crates/agglayer-node/src/rpc/tests/mod.rs, crates/agglayer-prover/src/executor.rs, crates/agglayer-prover/src/lib.rs, crates/agglayer-storage/src/columns/latest_pending_certificate_per_network/mod.rs, crates/agglayer-storage/src/columns/mod.rs, crates/agglayer-storage/src/storage/cf_definitions/pending.rs, crates/agglayer-storage/src/storage/mod.rs, crates/agglayer-storage/src/stores/interfaces/reader.rs, crates/agglayer-storage/src/stores/interfaces/writer.rs, crates/agglayer-storage/src/stores/pending/mod.rs, crates/agglayer-storage/src/tests/mocks/pending_store.rs, crates/agglayer/src/cli.rs, crates/agglayer/src/main.rs, crates/pessimistic-proof-test-suite/src/runner.rs, tests/e2e/helpers/cdk.bash, tests/e2e/helpers/common.bash, tests/e2e/helpers/kurtosis.bash, tests/e2e/regression-bali-balanceroot.bats
This PR is adding:
- a regression test script using `kurtosis` and `bats` (regression tests need to be completed to make it runnable on CI)
- two new RPCs are available:
- `getLatestSettledCertificateHeader` to get the latest settled certificate header for a network
- `getLatestPendingCertificateHeader` to get the latest pending certificate header for a network
- A new cli command `vkey` to show the current vkey of the pp
=> test: adding regression test e2e + RPCs + vkey CLI command

.github/labeler.yml, .github/workflows/labeler.yml
This PR is adding `labeler` in order to tag PR that are updating the `pessimistic-proof` program.
=> build: adding labeler workflow

crates/agglayer-certificate-orchestrator/Cargo.toml, crates/pessimistic-proof/src/local_state.rs
This PR is addressing some fixes for the nightly doc generation.
=> build: fixing doc generation

crates/agglayer-aggregator-notifier/src/packer/mod.rs, crates/agglayer-config/src/outbound.rs, tests/integrations/tests/certificate_settlement/l1_settlement/failure.rs
This PR is backporting #487 into `release/0.2.0`
=> chore: backport #487 in 0.2.0

README.md
README instructions to help people clone, install, and run AggLayer
=> docs: Update README files to improve comprehensiveness

.github/labeler.yml
This PR is updating the labeller config to match the new crates layout.
=> fix: update labeller to better tag pp changes

crates/pessimistic-proof-core/src/local_exit_tree/mod.rs, crates/pessimistic-proof/src/local_exit_tree/data.rs
Improve pessimistic-proof comments
=> chore: improve pessimistic-proof comments

crates/agglayer-certificate-orchestrator/src/network_task.rs, crates/agglayer-certificate-orchestrator/src/network_task/tests.rs, crates/agglayer-storage/Cargo.toml, tests/integrations/Cargo.toml
=> fix: handle jammed epoch channel in network task

crates/agglayer-aggregator-notifier/src/packer/mod.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-config/src/lib.rs, crates/agglayer-config/src/rpc.rs, crates/agglayer-config/tests/snapshots/auth_config__auth_kebab_case.snap, crates/agglayer-config/tests/snapshots/backup__backup_enabled.snap, crates/agglayer-config/tests/snapshots/validate_deserialize__empty_rpcs.snap, crates/agglayer-config/tests/snapshots/validate_deserialize__grpc_max_decoding_message_size.snap, crates/agglayer-config/tests/snapshots/validate_deserialize__max_rpc_request_size.snap, crates/agglayer-node/src/epoch_synchronizer.rs, crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/node.rs, crates/agglayer-node/src/rpc/admin.rs, crates/agglayer-node/src/rpc/error.rs, crates/agglayer-node/src/rpc/mod.rs, crates/agglayer-node/src/rpc/tests/get_certificate_header.rs, crates/agglayer-node/src/rpc/tests/mod.rs, crates/agglayer-node/src/rpc/tests/send_certificate.rs, crates/agglayer-storage/src/error.rs, crates/agglayer-storage/src/stores/interfaces/writer.rs, crates/agglayer-storage/src/stores/per_epoch/mod.rs, crates/agglayer-storage/src/stores/per_epoch/tests.rs, crates/agglayer-storage/src/tests/mocks/per_epoch_store.rs, crates/agglayer/tests/snapshots/config__config_display.snap, tests/integrations/src/agglayer_setup.rs, tests/integrations/tests/certificate_settlement/l1_settlement/failure.rs, tests/integrations/tests/certificate_settlement/retries.rs
This PR is addressing some improvement to reduce the risk of having unwanted certificate replacement.
=> feat: update the RPC to check for transaction status

crates/agglayer-node/src/kernel/mod.rs, crates/agglayer-node/src/kernel/tests.rs, crates/agglayer-node/src/rpc/error.rs, crates/agglayer-node/src/rpc/tests/errors.rs, crates/agglayer-node/src/rpc/tests/mod.rs, crates/agglayer-node/src/rpc/tests/send_certificate.rs, crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__cert_sig.snap, crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_invalid_len.snap, crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_recov.snap, crates/agglayer-node/src/rpc/tests/snapshots/agglayer_node__rpc__tests__errors__sig_verif.snap, crates/agglayer-node/src/service/error.rs, crates/agglayer-node/src/service/mod.rs, crates/agglayer-types/src/lib.rs
Forward-port #558 to main
Closes #553
=> feat: confirm certificates’ claimed emitter is allowed to emit

crates/agglayer-certificate-orchestrator/src/network_task.rs, crates/agglayer-certificate-orchestrator/src/network_task/tests.rs, tests/integrations/Cargo.toml
=> fix: handle jammed epoch channel in network task [`main` port]

crates/agglayer/src/cli.rs
Fix the restore command path calculation.
=> fix: restore command path

crates/agglayer-certificate-orchestrator/src/network_task.rs
Miscellaneous improvements found while reading `NetworkTask::make_progress`.
The `height` changes are a no-op, because all the match branches were returning the same value.
The logging changes are the only change here, because I’d expect at-capacity epochs to warrant a warning, because it means that the agglayer is under-powered compared to its use.
=> chore: improve code a bit around NetworkTask::make_progress

crates/agglayer-node/src/kernel/tests.rs, crates/agglayer-node/src/rpc/tests/send_certificate.rs
Handles review comments from #565
=> chore: miscellaneous improvements around verify_tx/cert_signature tests

.github/workflows/test.yml
This PR is redefining the kurtosis git ref for e2e tests.
=> fix: end2end tests still need a fix kurtosis version

Cargo.lock, Cargo.toml, crates/agglayer-aggregator-notifier/Cargo.toml, crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-aggregator-notifier/src/certifier/tests.rs, crates/agglayer/Cargo.toml, crates/agglayer/src/main.rs, tests/integrations/src/agglayer_setup.rs
This PR is updating how we start the agglayer prover from the agglayer-cli
=> refactor: agglayer-prover integration with provers

Cargo.lock, crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-aggregator-notifier/src/certifier/tests.rs, crates/agglayer-config/src/lib.rs, crates/agglayer-node/src/node.rs
This PR is updating agglayer to support mock verifier and is compatible with kurtosis-cdk in mock mode.
=> feat: make mock prover work with kurtosis-cdk

crates/agglayer-config/src/storage/backup.rs, crates/agglayer-config/tests/snapshots/backup__backup_enabled.snap
This PR is porting the changes from 0.2.2 for PR #562
(cherry picked from commit 78f56e8341ad320b3f5164720933a7e40152acda)
=> fix: fixing backup config format (#562)

tests/integrations/src/l1_setup.rs
=> test: detect docker failure in integration tests

.github/workflows/cycle-tracker.yml, .github/workflows/doc.yml, .github/workflows/docker-build.yml, .github/workflows/test.yml
This PR updates the kind of runner we're using for certain job.
=> build: update ci to use better runner

.github/workflows/proto.yml, crates/agglayer-signer/src/lib.rs
This PR is adding approval to proto workflow for merge_group
=> build: improve merge-queue-proto

.github/workflows/test.yml, Makefile.contracts.toml, crates/pessimistic-proof-test-suite/src/forest.rs, tests/integrations/Cargo.toml, tests/integrations/src/agglayer_setup.rs, tests/integrations/tests/certificate_settlement/concurrency.rs, tests/integrations/tests/certificate_settlement/happy_path.rs, tests/integrations/tests/certificate_settlement/l1_settlement/failure.rs, tests/integrations/tests/certificate_settlement/main.rs, tests/integrations/tests/certificate_settlement/retries.rs, tests/integrations/tests/certificate_settlement/retries/recovery.rs, tests/integrations/tests/common/mod.rs, tests/integrations/tests/storage_backups/main.rs
This PR is updating the setup for the integration tests.
It solves some problem with the setup itself on the CI.
But also improve the tests by clustering them per network type
=> build: update integration tests since contract update

.cargo/audit.toml
This PR updates the list of ignored `cargo audit` report
=> build: update cargo audit ignore list

.github/workflows/test.yml
This is a minor refactor to run the kurtosis tests in the `agglayer/e2e` repo.
=> ci: switching to agglayer e2e

README.md
=> docs: update detailed documentation link

Cargo.lock, crates/agglayer-rpc/src/lib.rs
Updates the check of the signature to not fail if we have expected empty signature.
=> feat: update signature verification logic

codecov.yml
=> feat: no code coverage for generated files

.github/workflows/coverage.yml
Fix coverage job by removing unused `cargo sonar`
=> build: simplify Clippy step in coverage workflow

crates/agglayer-node/src/epoch_synchronizer.rs
- handle all `TryRecvError` variants in epoch synchronization
> Add detailed handling for `TryRecvError` variants (`Closed`, `Lagged`, `Empty`) in the epoch synchronization logic to improve robustness and logging.
- add debug logs and validation for epoch synchronization
> Include additional debug logs for better traceability and add a validation check to ensure the current epoch is not less than the latest settled epoch.
=> fix: improve epoch_synchronizer logs and error handling

crates/agglayer-aggregator-notifier/src/certifier/mod.rs
Use deferred proof verification for the mock proofs in the sp1 native execution, only if in mock mode.
=> feat: deferred proof verification for the sp1 native execution

crates/agglayer-aggregator-notifier/src/packer/mod.rs, crates/agglayer-certificate-orchestrator/src/error.rs, crates/agglayer-certificate-orchestrator/src/lib.rs, crates/agglayer-certificate-orchestrator/src/network_task/tests.rs, crates/agglayer-clock/src/time.rs, crates/agglayer-config/src/lib.rs, crates/agglayer-config/src/log.rs, crates/agglayer-contracts/src/lib.rs, crates/agglayer-contracts/src/settler.rs, crates/agglayer-jsonrpc-api/src/admin.rs, crates/agglayer-jsonrpc-api/src/kernel/mod.rs, crates/agglayer-jsonrpc-api/src/tests/get_certificate_header.rs, crates/agglayer-node/src/node/api/tests/mod.rs, crates/agglayer-storage/src/storage/backup/mod.rs, crates/agglayer-storage/src/stores/per_epoch/mod.rs, crates/agglayer-storage/src/stores/per_epoch/tests.rs, crates/agglayer-types/src/lib.rs, crates/agglayer/src/cli.rs, crates/agglayer/src/main.rs, crates/pessimistic-proof-core/build.rs, crates/pessimistic-proof-test-suite/src/bin/convertor.rs, tests/integrations/src/agglayer_setup.rs, tests/integrations/src/l1_setup.rs, tests/integrations/tests/certificate_settlement/l1_settlement/failure.rs, tests/integrations/tests/storage_backups/main.rs
Fixes for clippy version 0.1.88, mostly printout formatting.
=> fix: clippy 0.1.88

Cargo.lock, Cargo.toml, crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-certificate-orchestrator/src/error.rs, crates/agglayer-storage/src/types/certificate/mod.rs, crates/agglayer-storage/src/types/certificate/tests/mod.rs, crates/agglayer-types/src/lib.rs, crates/pessimistic-proof-core/src/proof.rs, crates/pessimistic-proof-program/Cargo.lock, crates/pessimistic-proof-test-suite/aggchain-proof-ecdsa-example/lib/src/lib.rs
If the aggchain proof public values are provided in the certificate context, then we compare them with the ones expected by the PP.
Relates to #821
=> feat: propagate and compare the aggchain proof pv

.github/workflows/pr-review-reminder.yml
Adjust PR review reminder inputs
=> chore: adjust input pr review reminder

.github/workflows/release.yml
Backport of https://github.com/agglayer/agglayer/pull/884
=> feat: allow tagging post-releases

crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-node/src/lib.rs
Fixes https://github.com/agglayer/agglayer/issues/931
(cherry picked from commit 15c93ae16b4f88d652a98e9b4ae2d87964eb07e3)
=> fix: run expensive computation in a blocking task (#933)

crates/agglayer-certificate-orchestrator/src/network_task.rs
Remove unused member from `NetworkTask`.
Fixes https://github.com/agglayer/security/issues/132
=> fix: pending state member field

.github/workflows/doc.yml
This PR is a test of closing a PR and making sure the CF worker gets deleted correctly.
=> [WIP] chore: testing a fake PR opening

.github/workflows/doc.yml
This is another attempt at testing PR merging and the CF worker deletion job.
=> [WIP] ci: test closing pr

.github/pull_request_template.md, CONTRIBUTING.md
Part of https://github.com/agglayer/agglayer/issues/940
Fixes #492
=> docs: add contributing guidelines

crates/agglayer-rpc/src/error.rs, crates/agglayer-rpc/src/lib.rs
Add last settled claim for get network state
=> feat: add settled claim

Cargo.lock, crates/agglayer-rpc/src/lib.rs
If db get network info fails, proceed with alternative data collection methods.
=> fix: get network info

crates/agglayer-aggregator-notifier/src/certifier/l1_context.rs, crates/agglayer-aggregator-notifier/src/certifier/mod.rs, crates/agglayer-aggregator-notifier/src/certifier/tests.rs, crates/agglayer-aggregator-notifier/src/settlement_client/rpc.rs, crates/agglayer-aggregator-notifier/src/settlement_client/tests.rs, crates/agglayer-certificate-orchestrator/src/certificate_task.rs, crates/agglayer-certificate-orchestrator/src/certifier.rs, crates/agglayer-certificate-orchestrator/src/network_task/tests/status.rs, crates/agglayer-certificate-orchestrator/src/tests.rs, crates/agglayer-certificate-orchestrator/src/tests/mocks.rs, crates/agglayer-contracts/src/lib.rs, crates/agglayer-contracts/src/rollup.rs, tests/integrations/tests/certificate_settlement/retries/recovery.rs
Backport and adapt #1077 
Fixes https://github.com/agglayer/agglayer/issues/1076
=> fix: update witness_generation to accept a tx hash
